version: "3"
services:
  web:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./app:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./app/
    depends_on:
      - postgres
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    volumes:
      - ./app:/code
      - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app:/var/www/html
  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    volumes:
      - ./app:/code
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project
      - POSTGRES_PASSWORD=postgres
